#!/usr/bin/env bash
# Dogfood launcher for a plugin that vendors this toolkit. Vendored at
# <root>/plugin-dev/dogfood.sh; <root> is always found from the script's own
# location, never from CLAUDE_PROJECT_DIR or a hook payload's cwd (a resumed
# session can carry a foreign one).
#
#   sync           mirror the plugin tree into <root>/dist/plugin/
#   pre-tool       PreToolUse hook: read the payload on stdin, deny an edit
#                  into <root>/dist/plugin/; exit 0 on either verdict, empty
#                  stdout when allowing
#   session-start  SessionStart hook: warn when this session does not load
#                  <root>/dist/plugin/, or when jq is missing; exit 0,
#                  empty stdout when silent
set -euo pipefail
unset CDPATH # else a relative cd searches it and prints its target

main() {
    case "${1:-}" in
        sync) sync_copy ;;
        pre-tool) pre_tool ;;
        session-start) session_start ;;
        *) usage ;;
    esac
}

usage() {
    echo "usage: dogfood.sh sync|pre-tool|session-start" >&2
    exit 2
}

# The copy is the source tree minus what git ignores, minus .git, minus the
# copy itself. rsync gets the ignored paths as an exclude list, each anchored
# with a leading slash and NUL-separated, so a name holding a space or a
# newline survives. The list is written out in full before rsync starts: fed
# through a pipe, a git failure would leave rsync running on a partial list,
# copying .git and recursing into the copy. Deletions propagate: a path that
# stops being source leaves the copy. rsync's stderr is left alone, and its
# exit status is the script's. An entry holding * ? [ ] or a backslash aborts
# the sync before rsync runs or dist/ is touched: rsync reads the first four as
# wildcards and a backslash as an escape only when a wildcard is present, so
# such names are refused rather than escaped. The exit leaves only the loop's
# subshell; errexit ends the script on the pipeline's status, which is the
# loop's 1 even when git dies of SIGPIPE (pipefail reports the rightmost).
# Before anything else touches the tree, sync refuses a root with no plugin
# manifest and a root where git does not ignore dist/plugin/; each refusal is
# one dogfood: line naming the path, exit 1, dist/ untouched.
sync_copy() {
    local root
    root="$(root_dir && printf x)"
    root="${root%x}"
    require_manifest "$root"
    require_ignored_copy "$root"
    # Not local: the EXIT trap reads it after sync_copy has returned.
    excludes="$(mktemp "${TMPDIR:-/tmp}/dogfood.XXXXXX")"
    trap 'rm -f "$excludes"' EXIT
    git -C "$root" ls-files -z -o -i --exclude-standard --directory |
        while IFS= read -r -d '' entry; do
            case "$entry" in
                *'*'* | *'?'* | *'['* | *']'* | *\\*)
                    printf "dogfood: ignored entry '%s' holds a pattern character (* ? [ ] or \\\\); sync refused\n" "$entry" >&2
                    exit 1
                    ;;
            esac
            printf '/%s\0' "$entry"
        done >"$excludes"
    printf '%s\0' '.git' '/dist/plugin/' >>"$excludes"
    mkdir -p "$root/dist/plugin"
    rsync -a --delete --delete-excluded --from0 --exclude-from=- \
        "$root/" "$root/dist/plugin/" <"$excludes"
}

# The copy is regenerated by sync, so an edit into it is lost and never reaches
# the source. The verdict goes on permissionDecisionReason, worded to read after
# Claude Code's "PreToolUse:<Tool> hook error:" prefix and offering no way past
# the refusal, sync included: a mid-session sync is a promotion nobody asked
# for. The source path goes on additionalContext, naming the denied path too,
# since it arrives apart from the tool result; systemMessage is the one line for
# the human. The object is built with jq --arg, never spliced. The edited path
# is compared by its physical spelling against the physical <root>, so a
# symlinked spelling of the copy is caught; the source path is derived from that
# spelling too. An existing path that ends in a symlink is resolved in full with
# readlink -f, chains included, as Claude Code's own check resolves it. A leaf
# link that does not resolve (dangling, looping, or through a directory that
# cannot be entered) is compared as spelled, so a Write through a dangling one
# into the copy is not refused here. A payload jq cannot read, or a directory on
# the path that cannot be entered, stops the script non-zero: Claude Code shows
# a non-blocking hook error, and its own sensitive-file ask still stands before
# an edit into the copy. With no jq on PATH the guard stands down in silence
# rather than fail every edit of the session; the session-start warning is
# where a missing jq is reported.
pre_tool() {
    local root path physical rel copy="dist/plugin"
    command -v jq >/dev/null || exit 0
    root="$(root_dir && printf x)"
    root="${root%x}"
    # NotebookEdit names its target notebook_path, not file_path. Each x shields
    # a trailing newline in the path from its capture's strip.
    path="$(jq -j '.tool_input.file_path // .tool_input.notebook_path // ""' && printf x)"
    path="${path%x}"
    physical="$(physical_path "$path" && printf x)"
    physical="${physical%x}"
    # physical_path resolves directories only. -n keeps readlink's own newline
    # out of the capture; the x shields a newline in the name.
    if [[ -L "$physical" && -e "$physical" ]]; then
        physical="$(readlink -fn -- "$physical" && printf x)"
        physical="${physical%x}"
    fi
    case "$physical" in
        "$root/$copy/"*) ;;
        *) exit 0 ;;
    esac
    rel="${physical#"$root/$copy/"}"
    jq -nc --arg path "$path" --arg src "$root/$rel" --arg copy "$copy" '{
        hookSpecificOutput: {
            hookEventName: "PreToolUse",
            permissionDecision: "deny",
            permissionDecisionReason: ($path + " is in " + $copy + "/, the generated copy of this plugin. Edits to the copy are refused."),
            additionalContext: ("The source of " + $path + " is " + $src + ". Make the edit there.")
        },
        systemMessage: ("dogfood: blocked an edit into " + $copy + "/ — the generated copy")
    }'
}

# Silent when some ":"-separated entry of CLAUDE_CODE_PLUGIN_DIRS is
# <root>/dist/plugin, each entry compared whole, never by prefix, suffix or
# substring. An absolute entry naming a directory that can be entered is
# resolved with physical_path, since Claude Code writes the variable back
# normalized and a symlinked spelling must still match. Any other entry is
# compared as spelled, trailing slashes stripped: a relative one, which Claude
# Code drops, never matches, and one that cannot be entered puts no cd error on
# stderr. Anything else, unset included, gets one object. The payload is not
# read. systemMessage is the one line for the human, opening with an ANSI reset
# so Claude Code does not dim it like routine hook output; it names the remedy,
# launching through the shim. additionalContext gives the agent the same
# finding as a fact and nothing to act on: no command, no way to make the
# session load the copy. The object is built with jq --arg, never spliced.
# Without jq there is no object to build and no copy guard in pre-tool, so the
# check is skipped and a static systemMessage says so; it stays off the agent's
# channel, since only the human can install jq.
session_start() {
    local root copy rest entry
    if ! command -v jq >/dev/null; then
        printf '%s\n' '{"systemMessage":"\u001b[0mdogfood: jq is not on PATH, so the copy guard and this check are off until it is installed"}'
        exit 0
    fi
    root="$(root_dir && printf x)"
    root="${root%x}"
    copy="$root/dist/plugin"
    # Split by parameter expansion: the entries may hold spaces.
    rest="${CLAUDE_CODE_PLUGIN_DIRS:-}:"
    while [[ -n "$rest" ]]; do
        entry="${rest%%:*}"
        rest="${rest#*:}"
        [[ -n "$entry" ]] || continue
        if [[ "$entry" == /* && -d "$entry" && -x "$entry" ]]; then
            # The x shields a trailing newline from the capture's strip.
            entry="$(physical_path "$entry" && printf x)" || continue
            entry="${entry%x}"
        else
            while [[ "$entry" == */ ]]; do entry="${entry%/}"; done
        fi
        [[ "$entry" == "$copy" ]] && exit 0
    done
    jq -nc --arg copy "$copy" '{
        systemMessage: ("\u001b[0m" + "dogfood: this session does not load " + $copy + " — launch claude through plugin-dev/bin/claude from the repo root"),
        hookSpecificOutput: {
            hookEventName: "SessionStart",
            additionalContext: ("This session does not load " + $copy + ", so plugin behaviour observed in it is not that of the promoted copy.")
        }
    }'
}

# physical_path: the path where an edit would land, printed with no trailing
# newline. A subshell walks it one name at a time, entering each existing
# directory with cd -P, so a symlink anywhere up to the nearest existing
# ancestor resolves. From the first name that is not an existing directory on,
# the rest is kept as spelled, since an edit may create it, with each ..
# dropping the name before it: the kernel cannot resolve a .. past a directory
# that is not there yet, and the edit lands there whether the path is
# normalised first or its missing directories are made first. Names are split
# with parameter expansion and the result read from $PWD, never through a
# $(...) capture, which would strip a name's trailing newline. Each cd is
# chained, since errexit is off inside $(...): a failed cd must fail the call,
# not print a half-resolved path.
physical_path() {
    [[ -n "$1" ]] || return 0
    (
        local rest="$1/" name tail=""
        if [[ "$1" == /* ]]; then cd -P /; else cd -P .; fi || exit 1
        while [[ -n "$rest" ]]; do
            name="${rest%%/*}"
            rest="${rest#*/}"
            case "$name" in
                "" | .) ;;
                ..)
                    if [[ -n "$tail" ]]; then
                        tail="${tail%/*}"
                    else
                        cd -P .. || exit 1
                    fi
                    ;;
                *)
                    # An absolute operand names the directory in cd's error
                    # and keeps one named - from reading as cd -.
                    if [[ -z "$tail" && -d "$name" ]]; then
                        cd -P -- "${PWD%/}/$name" || exit 1
                    else
                        tail="$tail/$name"
                    fi
                    ;;
            esac
        done
        printf '%s' "${PWD%/}$tail"
    )
}

require_manifest() {
    if [[ ! -f "$1/.claude-plugin/plugin.json" ]]; then
        printf 'dogfood: %s/.claude-plugin/plugin.json not found; sync refused\n' "$1" >&2
        exit 1
    fi
}

# The trailing slash matters: a first sync has no dist/plugin yet, and git
# check-ignore on the bare name misses a /dist/plugin/ pattern. check-ignore
# exits 1 for "not ignored" and 128 for a git error; only the 1 is a refusal,
# a git error stops the script with git's own stderr.
require_ignored_copy() {
    local status=0
    git -C "$1" check-ignore -q dist/plugin/ || status=$?
    case "$status" in
        0) ;;
        1)
            printf 'dogfood: %s/dist/plugin/ is not git-ignored; sync refused\n' "$1" >&2
            exit 1
            ;;
        *) exit "$status" ;;
    esac
}

# root_dir: the physical parent of this script's directory, printed with no
# trailing newline and read from $PWD, never through a $(...) capture, so a
# root whose name ends in a newline keeps it; each caller shields its own
# capture with an x. The x after dirname shields the script directory's name
# the same way, and ?x drops dirname's own newline with it. Runs inside $(),
# where errexit is off, so each step is chained: a failed dirname must fail the
# call, not fall through to the parent of an empty path, which is /.
root_dir() {
    local here
    here="$(dirname "${BASH_SOURCE[0]}" && printf x)" &&
        (cd -P -- "${here%?x}/.." && printf '%s' "$PWD")
}

main "$@"
